-- Schema inicial do imóvel (equivalente ao que o Hibernate gerava antes, com o proprietário
-- ainda como texto). Num banco que já existia, esta versão é "baselined" e não roda de novo.
CREATE TABLE imovel (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario  VARCHAR(120),
    municipio     VARCHAR(120),
    uf            VARCHAR(2),
    bairro        VARCHAR(100),
    rua           VARCHAR(150),
    numero        VARCHAR(10),
    latitude      NUMERIC(10, 7),
    longitude     NUMERIC(10, 7),
    area_m2       NUMERIC(12, 2),
    ativo         BOOLEAN,
    criado_em     TIMESTAMP WITH TIME ZONE,
    atualizado_em TIMESTAMP WITH TIME ZONE
);
