-- Promove o proprietário de texto solto em cada imóvel para entidade própria, preservando os
-- imóveis já cadastrados. Nenhuma linha de imovel é perdida — só ganha uma FK.

-- 1. tabela de proprietários
CREATE TABLE proprietario (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE
);

-- 2. um proprietário por nome distinto já existente (TRIM evita duplicar por espaço à toa)
INSERT INTO proprietario (nome)
SELECT DISTINCT TRIM(proprietario)
FROM imovel
WHERE proprietario IS NOT NULL AND TRIM(proprietario) <> '';

-- 3. coluna FK, ainda anulável enquanto fazemos o backfill
ALTER TABLE imovel ADD COLUMN proprietario_id BIGINT;

-- 4. liga cada imóvel ao seu proprietário
UPDATE imovel i
SET proprietario_id = p.id
FROM proprietario p
WHERE p.nome = TRIM(i.proprietario);

-- 5. agora que todo imóvel tem dono, torna obrigatório + FK + índices
ALTER TABLE imovel ALTER COLUMN proprietario_id SET NOT NULL;
ALTER TABLE imovel ADD CONSTRAINT fk_imovel_proprietario
    FOREIGN KEY (proprietario_id) REFERENCES proprietario (id);
CREATE INDEX idx_imovel_proprietario ON imovel (proprietario_id);
CREATE INDEX idx_imovel_municipio ON imovel (municipio);

-- 6. o nome agora vive só em proprietario; a coluna texto não é mais necessária
ALTER TABLE imovel DROP COLUMN proprietario;
